version: '3.6'
services:
  api:
    image: filatovw/ni-storage
    ports:
      - 8555:8080
    environment:
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: "8080"
    volumes:
      - ./data:/var/lib/data